### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by trianity** [trilbymedia/grav-plugin-flex-objects#100]
The plugin installation failed:

![ScreenShot_20210121122834](https://user-images.githubusercontent.com/6353141/105345449-92e3b600-5be4-11eb-88f9-fe8fa682e260.png)

The error exists from admin panel side and from cli command side also.

Environment:
PHP 7.4.13
Grav v1.7.1 - Admin v1.10.1

**Comment by mahagr** [comment]
Try to clear cache first `bin/grav clear --all` and try again.

**Comment by trianity** [comment]
@mahagr  Thanks for the idea. The installation finished after clearing the cache.
