### ISSUE TITLE
twig files gone after update

### ISSUE THREAD

**Issue by PeterB513** [trilbymedia/grav-plugin-flex-objects#101]
I played around with the beta version of Grav 1.7 using the beta version of this plugin. I created a book catalog with this plug and put the twig files in flex/books/collection and object.This worked fine. After upgrade to 1.7 Grav and Flex-objects v1.0.1 my twig files were gone. The yaml file and the json data file were there. 
My questions is, is there a guideline were to put my own twig files for this plugin. Will the whole flex/ directory upgraded after a new version of the plugin? Because I want to make more catalogs of other goods and be sure that nothing will be overwritten. Thanks.

**Comment by mahagr** [comment]
All files in plugins will be removed on every single update. From themes, all the files distributed in the theme will be gone. Also everything in the `assets/`, `bin/`, `system/`, `vendor/` and `webserver-configs/` are not safe as Grav update will destroy anything in those.

**Comment by PeterB513** [comment]
Clear. But are there no rules of thumb where to place your own twig files and other stuff? Suppose I want to make all kinds of collections It has to be well organised. Perhaps I am to much a newbie in Grav.

**Comment by rhukster** [comment]
The simplest place to put twig files is in your theme in the templates folder.  Just keep the folder structure the same as it is in flex’s templates folder. 

Alternatively you can create a custom plugin and put them in that plugin’s templates folder.   You also have to add the plugins template path but it’s simple and you can find examples in pretty much every plugin (including flex).
