### ISSUE TITLE
templates are not found when plugin has admin/templates

### ISSUE THREAD

**Issue by JohnMica** [trilbymedia/grav-plugin-flex-objects#103]
hi guys,

quick one for you

- download Grav + Admin (latest versions)
- install a plugin that has templates for `admin/templates/xxxxxx`
- no longer able to access the `pages` due to missing `flex-object.html.twig` template

I believe that it replaces the admin/templates instead of merging them with the plugin and so flex-object templates are no longer found ?

copying the `flex-object templates` in the plugin `admin/templates` solves this issue

as an example you could try  - install the leaflet address plugin

**Comment by mahagr** [comment]
Which plugin as the plugins should just add their own paths, not replace them with their own.

**Comment by mahagr** [comment]
I just installed leaflet plugin and everything just works. Plugins, in general, should just add their own folder into lookup, not replace it with their own (which would break every other plugin).
