### ISSUE TITLE
Question: HowTo flex events in own Plugin?

### ISSUE THREAD

**Issue by bkraegelin** [trilbymedia/grav-plugin-flex-objects#104]
I try to _intercept_ the **Delete User** function, I need to remove some allocated ressources of users outside Grav.

Looking into the code I found the events **onBeforeDelete** and **onAfterDelete** which seem to be the right way to do what I want. But the code looks very different to that, what I find in plugins. Like **onFormProcessed** or (my favorite) **onUserLoginRegister** from Login plugin.

Questions:
What is the difference between _triggerEvent_ and _fireEvent_?
How do I handle **onBeforeDelete**?
_I need to handle accounts only (how do I find out?) and I need the accounts user name._

Thanks,
Birger

**Comment by bkraegelin** [comment]
Current work:

Found out, _triggerEvent_ is a wrapper for _fireEvent_. And **onBeforeDelete** fires **onFlexObjectBeforeDelete**.
I registered this event, but my plugin function does not get called.

Any suggestions?
Thanks.

**Comment by mahagr** [comment]
If you enable debugger and install clockwork, it will show you all the events that were called. It looks like `onFlexObjectBeforeDelete` is among them. 

I also hooked into the event and it does fire. Did you forget to add it to `getSubscribedEvents()` method?

**Comment by bkraegelin** [comment]
Thanks. Yes, this is the solution.

I still have a problem, understanding event handling.

My plugin used `getSubscribedEvents()` for `onPluginsInitialized` only. I subscribed to other events using `$this->enable()` within my `function onPluginsInitialized()`. This approach worked with all other events. And this approach is documented in **Plugin Tutorial Step 6** and **Step 7**.

Is there any documentation about that?

**Comment by mahagr** [comment]
Enabling events later works only if the event gets fired after you have enabled the feature. Also in many times, admin events will be disabled.
