### ISSUE TITLE
Updating admin + flex objects breaks admin

### ISSUE THREAD

**Issue by osxfuse-updates** [trilbymedia/grav-plugin-flex-objects#107]
Hey there,

I'm trying to debug myself, but I can't figure it out. I've disabled all plugins and reinstalled a fresh copy of admin + dependencies. But this bug always pops up when flex-objects is installed. Removing it gives me a working admin, but with the flex-objects enabled sections not usable.

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/76974052/106899887-2f827980-66f6-11eb-9fe2-f602c135c7e9.png">

**Comment by rhukster** [comment]
What version of php are you on?

**Comment by mahagr** [comment]
@osxfuse-updates Looks like your plugin configuration is bad. Try deleting `user/config/plugins/flex-objects.yaml` or apply the changes from above commit.

**Comment by osxfuse-updates** [comment]
Version is php7.4 and config is straight from the install via gpm install command. Nothing modified.

**Comment by rhukster** [comment]
Try the fix @mahagr made here: https://github.com/trilbymedia/grav-plugin-flex-objects/commit/29de88f9bffb18d672ae3b1d0f9cd62c5e9fa9e4
