### ISSUE TITLE
Avatar of the user isn't saved

### ISSUE THREAD

**Issue by beamaria** [trilbymedia/grav-plugin-flex-objects#111]
I have just updated Grav to 1.7.6 and all the related plugins to the latest version.
 I've created a new superuser, but when I try to add an image to this user and then save this user nothing happens and no image is displayed in the back-end.
The folder "avatars" in user-->accounts does contain the image uploaded, though.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/e42ae653554d92ccb9325c1df829659ac7e90438

**Comment by beamaria** [comment]
Thanks Mathias, it works!
I corrected the files manually; will the changes be salved with the next update??

**Comment by mahagr** [comment]
Yes, if file permissions allow HTTP server to replace the files.

**Comment by beamaria** [comment]
I think that this fix should be made permanent in the next release of the plugin; it is very useful if there are two or more users with different roles

**Comment by mahagr** [comment]
The fix is already part of the release, I thought you asked if the update will work if you changed the files manually. So yes, it will be there. :)

**Comment by beamaria** [comment]
Sorry I wasn't clear ;-)

Thanks!
