### ISSUE TITLE
Fatal error on v1.0.3

### ISSUE THREAD

**Issue by Karmalakas** [trilbymedia/grav-plugin-flex-objects#114]
Fresh Grav 1.7.5 and up + Admin 1.10.5 and up
With Flex Objects 1.0.2 all is fine, but with 1.0.3 navigating to _/admin/flex-objects_ ends up with error

Makes impossible to use FO on Admin Panel

![image](https://user-images.githubusercontent.com/3602819/110714672-88b95d80-820c-11eb-8c48-b383b18ba9e8.png)

**Comment by izzyu91** [comment]
I can confirm this error.

Adding this block in 1414 fixed it for me:

```
if (!$object) {
    return $this->object ?: null;
}

**Comment by Karmalakas** [comment]
Or simply just changing the line to (as seen in screenshot I've added and commented out)
```php
$this->object = $object ?? $object->getForm()->getObject();
```
