### ISSUE TITLE
Error when activating "Accounts" in GRAV system configuration

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#12]
Fatal error:  Declaration of Grav\Framework\Flex\Traits\FlexMediaTrait::getStorageKey() must be compatible with Grav\Framework\Flex\FlexObject::getStorageKey(bool $master = false): string in /Users/pro/Sites/grav/test/system/src/Grav/Common/User/FlexUser/User.php on line 52

PHP 7.1.32
GRAV 1.7-beta.8

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/66bd6a4046044f63e34a7fe5cd5dc1c60b4fe34b
