### ISSUE TITLE
Overwrite flex page admin templates in own plugin

### ISSUE THREAD

**Issue by ChristianaHoJo** [trilbymedia/grav-plugin-flex-objects#122]
2 years ago we added some extra features (modals, functions etc) to the admin panel pages in old grav version. Therfore we copied admin templates into an own plugin to overwrite them.

Now I try to do the same changes for the new flex pages. 

I added  the template path and copied some template files from flex objects  plugin into my own one but still the flex objects templates are shown.
```
 public function onAdminTwigTemplatePaths($event)
    {
       // exclude other admin plugins or menu items
        if(in_array('pages',$this->grav['uri']->paths())) {         

            // Add plugin template path for admin.
            $paths = $event['paths'];
            $paths[] = __DIR__ . '/admin/themes/grav/templates';
             //add path for flex pages
            $paths[] = __DIR__ . '/admin/templates'; 
            $event['paths'] = $paths;
        }
    }
```
I would be glad to get an hint to this issue!

Greetings,
Christiana

**Comment by mahagr** [comment]
Sorry for the delay; you may want to give the event a different priority so that the paths you added will be a higher priority. Play with values 100 and -100 and see which one does the trick.
