### ISSUE TITLE
Error 404 when adding new contact

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#14]
When saving a new "Contacts" with option "create new item"
![image](https://user-images.githubusercontent.com/15226809/65314860-ae424980-dbc9-11e9-9482-d5a9b3f2c202.png)

it creates a 404 error

![image](https://user-images.githubusercontent.com/15226809/65314929-cca84500-dbc9-11e9-9fd9-73fa2094c0ad.png)

**Comment by rhukster** [comment]
Confirmed, this functionality never got added from FlexDirectory.

**Comment by lufog** [comment]
@mahagr, problem is not fixed on version ```1.0.0-beta.9```. When adding a new contact or account, I get to page 404. Add button link leads to ```/admin/accounts/action:add``` instead of ```/admin/accounts/action;add```.

**Comment by rhukster** [comment]
So seems it’s probably fine, just a param separator issue does you on windows.

**Comment by mahagr** [comment]
Fixed for next Grav beta (was an issue with Route class not being properly initialized).
