### ISSUE TITLE
ShortCode and External Links plugin issues

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-flex-objects#16]
Not sure if this is an existing issue... with Flex as frontend pages both the ShortCode and External Links plugins generate errors, as shown below:

![2019-09-20_08-11-53](https://user-images.githubusercontent.com/1812771/65338252-a3ae9280-db7e-11e9-9732-d7001caaff1e.png)

![2019-09-20_08-11-26](https://user-images.githubusercontent.com/1812771/65338259-a90bdd00-db7e-11e9-9e17-6284d57c1226.png)

Please let me know if any additional information is helpful.

Thank you,
Paul

**Comment by rhukster** [comment]
Actually I need to make some fixes in these plugins to use `PageInterface` rather than `Page` object directly. Will fix those up real quick and let you know.

**Comment by paulhibbitts** [comment]
Awesome, thanks @rhukster!

**Comment by rhukster** [comment]
Ok I pushed a commit for ShortcodeCore.  ExternalLinks is not one of ours, but you could try making similar changes as I did here: https://github.com/getgrav/grav-plugin-shortcode-core/commit/c374d81db2e5c4d76ff994b9916ef106530ffc79

**Comment by paulhibbitts** [comment]
Thanks @rhukster will test and report back.

**Comment by paulhibbitts** [comment]
Yes, that fix works here too with ShortCode👍I will leave a note on External Links Plugin re: the fix too.
