### ISSUE TITLE
Flex Pages: Context menu "Preview" error

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#17]
Clicking on the preview of the context menu creates following error:

Unable to find one of the following templates: "flex-objects/types/grav-pages/buttons/up.html.twig", "flex-objects/types/grav-pages/buttons/up.html.twig" in "flex-objects/types/grav-pages/preview.html.twig" at line 7.

![image](https://user-images.githubusercontent.com/15226809/65341026-09902e00-dc02-11e9-9032-180dfe578e3a.png)

**Comment by kiranetph** [comment]
Beta-9
click on preview icon creates error
![image](https://user-images.githubusercontent.com/15226809/65747232-7ee48d00-e133-11e9-884d-a437476fa466.png)

**Comment by mahagr** [comment]
Please create a new issue, Folder page type should not have a preview (not routable).

**Comment by rhukster** [comment]
https://github.com/trilbymedia/grav-plugin-flex-objects/issues/27
