### ISSUE TITLE
Flex Pages: Problem with Delete and context menu

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#18]
After clicking on context menu "Delete", then click "Cancel" at the confirmation dialog, the context menu of this page can not be opened anymore. Needs a page refresh ...

**Comment by w00fz** [comment]
I can't replicate this issue.

There must be something going on with your browser that is not happening on mine... Other issues you reported I am unable to replicate.

![2019-09-23 14 40 43](https://user-images.githubusercontent.com/11734/65465073-416cc080-de10-11e9-861f-81efe28a565b.gif)

**Comment by rhukster** [comment]
i can't replicate this either.

**Comment by w00fz** [comment]
Can try using the develop version for testing if it makes any difference?

**Comment by mahagr** [comment]
@kiranetph New beta released, you can try with it.

**Comment by kiranetph** [comment]
still the same ... if I cancel a delete, the same context menu does not show up anymore 
see:
![2019-09-27_13-54-33 (2)](https://user-images.githubusercontent.com/15226809/65745713-3034f400-e12f-11e9-863b-0bade73e5ce5.gif)

**Comment by mahagr** [comment]
Whihc browser do you use? Version?

**Comment by kiranetph** [comment]
Grav v1.7.0-beta.9
Admin v1.10.0-beta.9
Flex-Objects v1.0.0-beta.9

macOS 10.14.6
Safari 13.0.1
Chrome Version 77.0.3865.90
Firefox Developer Edition 70.0b9

ALL browser show the same behaviour.

**Comment by rhukster** [comment]
Are you getting any JS errors in the browser developer tools consoles?  Are you running any firewall software or anything?

I'm running same version of macOS with same safar/chrome/firefox versions as you and can't replicate this at all

**Comment by kiranetph** [comment]
I have a network monitor "Little Snitch" active, but disabled it for testing. Still the same.
Safari has only 1 Extension installed (1password 7), I deactivated it also - Still the same.

Safari console:
![image](https://user-images.githubusercontent.com/15226809/65807131-90737680-e1bf-11e9-95ae-5cdb5ff76e1b.png)

Firefox Developer edition console:
![image](https://user-images.githubusercontent.com/15226809/65807180-cd3f6d80-e1bf-11e9-9b6f-07d2762d4af8.png)

Chrome console:
![image](https://user-images.githubusercontent.com/15226809/65807250-0a0b6480-e1c0-11e9-8144-e0a6d56dc3ac.png)

installed through homebrew:
![image](https://user-images.githubusercontent.com/15226809/65807270-23141580-e1c0-11e9-8dfe-66dd4f9f6aec.png)

**Comment by w00fz** [comment]
This is actually same issue as #20
