### ISSUE TITLE
Flex Pages: Breadcrumb problem

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#19]
Example: when clicking on the 5th level, it will always open the 2nd level and not the 5th level

**Comment by rhukster** [comment]
I can't reproduce this either, seems to be a similar issue to #20

**Comment by kiranetph** [comment]
see animation:
![breadcrumb](https://user-images.githubusercontent.com/15226809/65451986-db655500-de72-11e9-82a7-3d190df7a264.gif)

**Comment by rhukster** [comment]
ok confirmed!
