### ISSUE TITLE
Flex Pages: Context menu position problem

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#20]
If you select the context menu on the 4th or higher level, it will show up only partial on the right side. It will also not show up properly on other pages.

![image](https://user-images.githubusercontent.com/15226809/65342876-3e9e7f80-dc06-11e9-880b-d2b5af563014.png)

**Comment by w00fz** [comment]
@kiranetph what browser are you using? I tested at a 5th and 6th level and the dropdown always align properly.

Can you share the pages you have (or a dummy replica) where this can be reproduced?

**Comment by kiranetph** [comment]
@woofz
Safari 13.0 under MacOS Mojave 10.14.6
but the same happened under Chrome 77.0.3865.90 
to reproduce it, ii attached a "pages" folder
[pages.zip](https://github.com/trilbymedia/grav-plugin-flex-objects/files/3641987/pages.zip)

Expand it until the 4th level and click the context menu icon. the context menu does not show up.
![image](https://user-images.githubusercontent.com/15226809/65424115-4c8a1580-de3d-11e9-84a9-fd20ebc96f29.png)

now click on the 3rd Level context menu icon:

![image](https://user-images.githubusercontent.com/15226809/65424194-7fcca480-de3d-11e9-8304-550e053e166c.png)

**Comment by rhukster** [comment]
Even using your pages.zip i'm unable to replicate this either.. Not sure what it could be...

**Comment by kiranetph** [comment]
Here it happens all the time. See the animation:
![context](https://user-images.githubusercontent.com/15226809/65450815-92140600-de70-11e9-8069-2a43120d39f5.gif)

**Comment by paulhibbitts** [comment]
I've also seen this exact behavior, on Safari. I can also duplicate in Firefox Mac:
![2019-09-23_13-57-39](https://user-images.githubusercontent.com/1812771/65462214-28611100-de0a-11e9-9660-cf9d6c60af61.png)

**Comment by w00fz** [comment]
That is different though @paulhibbitts , the issue we can't reproduce is the dropdown opening and not aligning with the `...` button. In your screenshot, granted it's going out of the screen, it is properly aligned as expected.

**Comment by paulhibbitts** [comment]
Oh I gotcha, sorry I did not catch that @w00fz ! I will also try to test with another level as shown.

**Comment by paulhibbitts** [comment]
Ok, I've been able to duplicate the issue with Firefox on Mac now:

![2019-09-23_14-17-51](https://user-images.githubusercontent.com/1812771/65463717-1f257380-de0d-11e9-8e7d-0302bb730521.png)

Here is my Pages folder:
https://ln2.sync.com/dl/017751020/yxi5su7b-97qj4tyc-ptum8pnv-pvipg8cy

If a screen sharing session with my local Browser is of help contact me on Discord.

Thanks,
Paul

**Comment by w00fz** [comment]
Even on firefox and with your pages it seems I'm unable to reproduce.

<img width="714" alt="Flex Pages | Grav 2019-09-23 14-46-54" src="https://user-images.githubusercontent.com/11734/65465391-06b75800-de11-11e9-85ce-471d97ef4207.png">

I also cannot reproduce the dropdown misaligned and going offscreen as you can see from my animated gif in https://github.com/trilbymedia/grav-plugin-flex-objects/issues/18#issuecomment-534296816

Not quite sure what's up.. maybe some changes pushed and not available to you yet?

**Comment by paulhibbitts** [comment]
Maybe? I will test this again next release, and my offer for a screen sharing session so you can take a closer look at this is still open🙂

**Comment by rhukster** [comment]
![image](https://user-images.githubusercontent.com/1084697/65561491-def2ed80-deff-11e9-8d8f-f0c1f5033a59.png)

Can't replicate this either

**Comment by w00fz** [comment]
Could you guys perhaps try using the develop version for testing if it makes any difference?

**Comment by paulhibbitts** [comment]
I saw this @w00fz , I will try this today and report back.

**Comment by paulhibbitts** [comment]
Here is what I am seeing with the current Develop branch (Latest commit
0e548ad):

![2019-09-26_09-24-52 (1)](https://user-images.githubusercontent.com/1812771/65706652-c12ca200-e03f-11e9-8afe-5601b1dd5f4d.gif)

**Comment by w00fz** [comment]
Maybe a plugin interfering? It's not supposed to open out to the right, should be opening out to the left: top-right corner of the dropdown aligned with the bottom-right corner of the `...` button.

**Comment by paulhibbitts** [comment]
Good idea, I disabled just about all Plugins and still seeing this type of behavior. Hopefully someone else might also see this to help triangulate things etc. Next Beta release I will also try a fresh build/test etc.

**Comment by paulhibbitts** [comment]
Ok, here is a demo of the latest beta 9:

![2019-09-26_13-48-32 (1)](https://user-images.githubusercontent.com/1812771/65724118-9739a680-e064-11e9-8a63-97af5f7c1345.gif)

Looks like the issue is the same, and also notice the second time I tap on a page options button the popup does not appear.

Please let me know if any more info is helpful etc.

**Comment by rhukster** [comment]
Hmm.. Paul we are struggling to recreate this.  Can you list all Grav plugins you are using? Also browser plugins?

**Comment by kiranetph** [comment]
I made a complete new installation just without any additional plugins and it is still the same problem. 
But it seems it might be related to screen and browser resolution. 
Just make the browser window smaller than the full screen size.
Will investigate it further in a while and report.

**Comment by mahagr** [comment]
Browser version? Screen resolution?

**Comment by kiranetph** [comment]
Grav v1.7.0-beta.9
Admin v1.10.0-beta.9
Flex-Objects v1.0.0-beta.9

macOS 10.14.6
Safari 13.0.1
Chrome Version 77.0.3865.90
Firefox Developer Edition 70.0b9

All browser show same behaviour.

Screen Resolution: 2560 x 1600
Browser width: 1800

If the Browser width is smaller than the screen resolution, the problem is there and some of the drop downs are not visible

If the browser resolution is full screen width, it seems the context menu shows up correctly (except the last level, where it only shows a little of the left side
![image](https://user-images.githubusercontent.com/15226809/65745199-7db06180-e12d-11e9-9e81-59a1e6683a55.png)

**Comment by w00fz** [comment]
I’m not sure that the resolution of the browser being smaller than the screen resolution is the cause. Both @rhukster and I are on Mac and we never use full screen browser, it’s always about 1/3 of the screen resolution.

**Comment by kiranetph** [comment]
here it gets "better" with a fullwidth browser window , but I noticed now a similar behaviour like in the "delete-cancel" problem.
It seems that if drop downs once show up, they don't show up anymore. 
The way "leaving" the dropdown, is to click somewhere right above on the window:
see:
![2019-09-27_14-09-14 (1)](https://user-images.githubusercontent.com/15226809/65746210-c4ec2180-e130-11e9-889a-251cb5041645.gif)

**Comment by paulhibbitts** [comment]
The issue persists on all of the below for me:

Grav v1.7.0-beta.9
Admin v1.10.0-beta.9
Flex-Objects v1.0.0-beta.9

macOS 10.14.6
Safari 13.0.1
Firefox 69.0.1
MS Edge Canary 79.0.285.0 (as shown below):

![2019-09-27_07-29-54 (1)](https://user-images.githubusercontent.com/1812771/65777353-bd108b00-e0f8-11e9-9548-26e67c390076.gif)

Example Browser resolution: 1200 x 842

**Comment by paulhibbitts** [comment]
Since Browser window size was mentioned by @kiranetph I thought I too would also test with a full-width Browser window. Position issues look better, but second taps still do not show popup:

![2019-09-28_13-54-28 (1)](https://user-images.githubusercontent.com/1812771/65822386-cfbdb980-e1f7-11e9-9bec-5a458786deb6.gif)

**Comment by rhukster** [comment]
@paulhibbitts have you tested with a fresh package: https://getgrav.org/download/core/grav-admin/1.7.0-beta.9?testing

Just trying to find a baseline as to what is causing this for you guys, when we can't reproduce it at all.

**Comment by paulhibbitts** [comment]
Sure thing, I downloaded the latest 1.7 beta with Admin, copied over my test pages, and saw the issue on Safari and Firefox as described.

If helpful, here is a ZIP of my entire Grav setup with the test page:
https://ln2.sync.com/dl/b36176030/cuvnp9xt-npw58gkg-26m6mnx9-4y8zwyrw

Happy to do further tests etc, I wish I could help more determining the exact issue but it is repeatable on my Mac and I am running 20+ local test Grav sites on the same setup.

**Comment by kiranetph** [comment]
@rhukster Maybe you have some sort of developer tools installed which we don't have?

I just reproduced the problem on another MacBook Pro...

**Comment by paulhibbitts** [comment]
Ok, I've done a few more tests - here are the results:

Mac Safe Mode boot-up, no change
Online hosting of Admin Beta, no change
Opera Browser, no change

The one good thing here is that I then tested the online Admin Beta test site on my Surface Pro with Firefox and things worked just fine, popup boxes displayed where expected and I was able to repeatedly tap to view popups.

**Comment by rhukster** [comment]
I'm guessing you would have trouble on my working sites too. It's something related to the browser itself, I don't think its grav or config related.

**Comment by paulhibbitts** [comment]
The puzzle for me is that it is occurring on all Browser on my Macbook Pro...

**Comment by rhukster** [comment]
Me also, as it appears on none of mine.

**Comment by paulhibbitts** [comment]
Ok, I've been able to test on a fresh MacBook Pro 13" (2016, Safari, latest Mac OS) now, and the same issue is there. Perhaps as @kiranetph mentioned might there be something on your dev Mac setups not on ours that is related?

**Comment by rhukster** [comment]
Funny i also tested on my wife's very basic "MBP 15" with chrome and it was also fine.  perhaps we can do a screenshare and see if there's something different you are doing? Let's chat on Discord.

**Comment by paulhibbitts** [comment]
Sure thing Andy!

**Comment by w00fz** [comment]
We were able to replicate the issue thanks to @paulhibbitts sharing with us the screen.

The issue appears to be caused by the setting in mac where the scrollbar is set to show only when scrolling.

I am now able to fully reproduce the issue and will be fixing asap.

Thanks!

**Comment by w00fz** [comment]
Got it fixed! 🎉 Please give it a go and let me know!

Thanks again for helping tracking down the issue.

**Comment by paulhibbitts** [comment]
Great work @w00fz , I can confirm the fix on my MacBook Pro too👍

**Comment by kiranetph** [comment]
Yehey ... now it is working as expected 👍
