### ISSUE TITLE
Flex Pages: Page Preview Icon not working

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-flex-objects#21]
When viewing the Options panel for a Page, tapping the Page Preview button results in a Twig error:

![2019-09-20_10-53-29](https://user-images.githubusercontent.com/1812771/65348034-204c6b80-db95-11e9-816f-7165abffd0bb.png)

Please let me know if additional info is helpful etc.

Thanks,
Paul

**Comment by mahagr** [comment]
Duplicate of #17
