### ISSUE TITLE
Flex Pages: Unexpectedly cannot view folder of Pages

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-flex-objects#23]
I've built a 1.7 Beta 8 skeleton of my MultiCourse Hub, but when I switch to "Flex Pages" for backend I cannot seem to display some sub-folders. Here is a video:

![2019-09-20_13-59-08 (1)](https://user-images.githubusercontent.com/1812771/65358784-4f6fd680-dbaf-11e9-9135-c9d68ece1309.gif)

Here is a ZIP of the test skeleton if helpful: https://ln2.sync.com/dl/0d004f180/2758tcxt-24s634j8-t5nsw8cy-trsx7dah

Thanks very much,
Paul

**Comment by rhukster** [comment]
Yes please provide a zip of the pages.

**Comment by rhukster** [comment]
Also check your XHR network traffic and any JS console errors

**Comment by paulhibbitts** [comment]
Thanks @rhukster , so I've made some progress I think in tracking it down... as I am more familair with the Dev tools in Chrome I tried that with the site and the Flex Pages nav all worked! The issue I am seeing seems to be connected with Safari... here is the page ZIP folder:

[pages.zip](https://github.com/trilbymedia/grav-plugin-flex-objects/files/3638145/pages.zip)

And here is what I see in the JS Console in Safari:
![2019-09-20_17-21-09](https://user-images.githubusercontent.com/1812771/65365066-22c9b800-dbcb-11e9-9eb5-872b40bfb731.png)

Any clues?

Thanks,
Paul

**Comment by rhukster** [comment]
Those errors are a bit above my pay-grade! Passing on to our resident Vue-JS guru :)
