### ISSUE TITLE
With flex-enabled, saving system.yaml loses `home: alias:`

### ISSUE THREAD

**Issue by rhukster** [trilbymedia/grav-plugin-flex-objects#25]
Home's parent field doesn't work in Flex causing a blank list, so `home: alias` always get clears out losing the homepage.

**Comment by mahagr** [comment]
Fixed in admin: https://github.com/getgrav/grav-plugin-admin/commit/4ff5f7c8d93b976f8fb6817bfb11a03716e29f36

Above fixes the issue, but we really should stop using `pages` field or make it an alias of `parents` field as this field will not work with large sites.
