### ISSUE TITLE
context menu "Preview" error for Folders

### ISSUE THREAD

**Issue by rhukster** [trilbymedia/grav-plugin-flex-objects#27]
![](https://user-images.githubusercontent.com/15226809/65747232-7ee48d00-e133-11e9-884d-a437476fa466.png)

**Comment by mahagr** [comment]
@rhukster I'm not getting this with latest develop, can you check if you are? I mean, there is no preview anymore.

**Comment by mahagr** [comment]
Looks like this was fixed in #24
