### ISSUE TITLE
[PHP 7.1] Error message

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#29]
PHP 7.1.32
Flex-objects v1.0.0-beta-10

![image](https://user-images.githubusercontent.com/15226809/66484901-70568800-eada-11e9-9dcf-8ba6fedd32b1.png)

**Comment by mahagr** [comment]
Good catch, I've been only running in PHP 7.3, I will do some testing in PHP 7.2 and 7.1, too.

**Comment by mahagr** [comment]
Should be fixed for the next version.
