### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by localnetwork** [trilbymedia/grav-plugin-flex-objects#35]
Call to undefined method Grav\Framework\File\Formatter\JsonFormatter::getFileExtension()

![scr1](https://user-images.githubusercontent.com/15809239/67857564-159cd300-fb52-11e9-9a35-4abe0faa2b67.jpg)

**Comment by rhukster** [comment]
Requires grav 1.7. You in latest?

**Comment by localnetwork** [comment]
I see, I'm using 1.6 (stable version.). Is there any way the i can switch to the beta version in command line? Or it's not recommended?

**Comment by rhukster** [comment]
Change the releases to testing in user/config/system.yaml and do a bin/gpm selfupgrade

**Comment by localnetwork** [comment]
Thanks @rhukster

**Comment by replayshot** [comment]
I get the same error with 1.7-RC1 and admin plugin 1.10.0-RC3. Any idea?
![err](https://user-images.githubusercontent.com/968902/73344581-44c6fb80-428b-11ea-9c35-7dfcc5c3f7a1.jpg)

**Comment by mahagr** [comment]
You need Grav, Admin and Flex Objects all using RC.3

**Comment by replayshot** [comment]
thanks. that seemed to do the trick.
