### ISSUE TITLE
Clicking on Flex Objects sidebar nav item in Admin results in Crikey! page -Grav 1.7rc1

### ISSUE THREAD

**Issue by SteveBaumann** [trilbymedia/grav-plugin-flex-objects#40]
After upgrading from Grav 1.7beta10 to 1.7rc1 and activating Flex Objects plugin and setting all options to Enabled, a Crikey! page results from clicking the Flex Objects nav item  in the Admin left sidebar. All other pages in Admin render normally, including Pages, which seems to be using the Flex interface/UI. 
![flex-objects-error-20191207](https://user-images.githubusercontent.com/11002590/70382064-bc6f4e80-190a-11ea-9ac8-544e329c3807.png)
Please let me know if I should add more details to this issue.

**Comment by mahagr** [comment]
Already fixed.
