### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()").

### ISSUE THREAD

**Issue by achwell** [trilbymedia/grav-plugin-flex-objects#42]
Installed Flex-Objects  v1.0.0-rc.2 on Grav v1.7.0-rc.2
Tried to go to /admin/contacts (from the left menu), and get this error:
![flexobjects](https://user-images.githubusercontent.com/91200/71151869-281fb880-2235-11ea-9545-a774d1cd07aa.png)

**Comment by achwell** [comment]
Tried to activate "Flex Accounts (Admin)" and "Flex User Groups (Admin)"
Same error  when clicking "User Accounts" or "User Groups" from left menu

**Comment by mahagr** [comment]
Bad translation in `GRAV.INFLECTOR_UNCOUNTABLE`? It should contain a list.

**Comment by mahagr** [comment]
This looks like Grav bug to me.

**Comment by achwell** [comment]
Fixed this by changing user/config/system.yaml :
translations: true

**Comment by mahagr** [comment]
Fixed in Grav 1.7.0-rc.4
