### ISSUE TITLE
Saving after enabling Flex-pages and/or Flex Pages (Admin) produces error message

### ISSUE THREAD

**Issue by SteveBaumann** [trilbymedia/grav-plugin-flex-objects#45]
In a bare install from the current 1.7 repo (as of 20200118), with Flex-Objects being the only extra plugin installed, aside from the initial 7 plugins, when trying to enable Flex-pages and/or Flex Pages (Admin): 
![image](https://user-images.githubusercontent.com/11002590/72688292-68838800-3aba-11ea-9145-375328bf725a.png)

The `Validation failed: admin_list is not defined in blueprints` error is produced: 
![image](https://user-images.githubusercontent.com/11002590/72688299-7afdc180-3aba-11ea-8d59-4ce8979670de.png)

**Comment by mahagr** [comment]
This has already been fixed for RC.4
