### ISSUE TITLE
changing page-template problem

### ISSUE THREAD

**Issue by AndrassGray** [trilbymedia/grav-plugin-flex-objects#48]
Environment : Grav 1.7 RC 6. Custom template inherited from Quark, I have a page-template called "Two-col" that is used by a page "contact". Two languages (fr and en), default language "fr". Yaml-linter is all green.

Wanting to try something, I changed the page-template to "Default" and saved. That sends me to a 404 page on the front-end side with the strange looking URL `http://vu/fr/fr/admin/pages/contact`

Going to the back-end, I find that the page is completely empty. Frontmatter empty. Page-content empty. The file still has its content.

Saving that page (for fun and giggles) throws red notices
```
Saisie non valide "Parent"
Save Failed: Form validation failed, please check your input
```

While trying to make sense of all this, I even have managed to empty the file somehow. But it's not repeatable.

I have the impression that the problem is only showing in Normal mode. And apart from the strange URL above, this does not seem related to the multi-language environment.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/993bc5170b2153227863f8bf7c578aa6ad11810c
