### ISSUE TITLE
Children Display Order setting discrepancy

### ISSUE THREAD

**Issue by onetrev** [trilbymedia/grav-plugin-flex-objects#53]
If I have Flex Objects _disabled_ then my **Children Display Order** is correct, and "Ordered by Collection definition" correctly shows the most recent pages (most recent blog posts) first. As soon as switch Flex Objects back on then it reverted to an alphabetical listing in ascending order. It seems to do so regardless of "Ordered by Collection" or "Ordered by Folder Name" when using Flex Objects.

**Comment by mahagr** [comment]
Looks like I missed this one. 

See also https://github.com/getgrav/grav/issues/2881

**Comment by mahagr** [comment]
Fixed in Grav, see above issue.
