### ISSUE TITLE
set order 

### ISSUE THREAD

**Issue by mmorkt** [trilbymedia/grav-plugin-flex-objects#57]
Is it possible to set the order on custom flex-objects?
Tried with .order but I'm getting an error:
```
{% set flex = grav['flex_objects'].directory('xxx').collection.order('field_in_flex_object') %}

{% for object in flex if object.published %}
   {{ object.field_in_flex_object }}
{% endfor %}
```
My work-around so far is to change the key and use the |sort filter.
I'm missing the sorting function used in the backend for pages (sortable pages).

**Comment by mahagr** [comment]
`.order({field: 'ASC'})` or just set default ordering from the blueprint.

**Comment by mmorkt** [comment]
Thank you @mahagr

**Comment by mmorkt** [comment]
Just tried it, but I'm still getting the same error:

```
Error
Call to undefined method Grav\Common\Flex\Types\Generic\GenericCollection::order()
```

Will try setting the order in the blueprint, thanks

**Comment by mahagr** [comment]
As I said, there's no order(), just sort().

Closing the issue.
