### ISSUE TITLE
With plugin enabled, onAdminSave event doesn't fire

### ISSUE THREAD

**Issue by mbirth** [trilbymedia/grav-plugin-flex-objects#58]
Since flex-objects seems to replace the admin plugin's `AdminController`, the events fired there are not fired. So other plugins using `onAdminSave` and/or `onAdminAfterSave` won't work anymore.

**Comment by mahagr** [comment]
This is basically because of some plugins seem to break if I used the old events. I think we just need to add a few configuration options for the events.

**Comment by mahagr** [comment]
Events were added in https://github.com/getgrav/grav/commit/3a05dcf6592dc9855bfea05c14171500923a3849

**Comment by NicoHood** [comment]
I am not sure if this is 100% compatible.

The original code:
https://github.com/getgrav/grav-plugin-admin/blob/06c66794cc391f6d29b0261019b0a850cd0a0b84/classes/admincontroller.php#L666

The new:
https://github.com/getgrav/grav/commit/3a05dcf6592dc9855bfea05c14171500923a3849#diff-01780a944f8c1d48066fed0f8b2391abe743e75a1b13a70ae9a4a938bd2a7a3cR243

I am not sure, I guess `page` must be renamed to `object`?

It seems those events are outdated anyways, so can you maybe point us to the new events that are able to modify the page correctly? Also is there an option to query for the grav version to subscribe to different events?

**Comment by mahagr** [comment]
Already fixed that long time ago:

https://github.com/getgrav/grav/blob/1.7/system/src/Grav/Common/Flex/Types/Pages/PageObject.php#L272

**Comment by NicoHood** [comment]
Oh, you are right! But what about `Switching Flex Page object during onAdminSave event is not supported! Please update plugin.`, how to migrate that? What is the new event to use?

**Comment by mahagr** [comment]
It means that you have replaced the page object in your plugin with another one. You shouldn't do that as it breaks the saving.

Instead of doing that, just modify the object before it gets saved.

**Comment by NicoHood** [comment]
Alright, so nothing will break. Thanks a lot for clarifying :-)

**Comment by NicoHood** [comment]
In my plugin I am checking the type of the `object` like this:
```php
if (!($page instanceof \Grav\Common\Page\Page)) {
    return;
}
```

Now this does not work with the new flexobject. The check is still required, as saving a plugin config also fires this event.

But even if I ignore the check for now all page content is cleared on safe. This is possibly because I am modifying the page and this fails. But no error message is displayed this could be improved. I am still searching for a solution. Is there a common way to support Flexpages and "normal/old" Pages?

**Comment by mahagr** [comment]
Yes, check against `PageInterface`, it is common to all page types. Header object as toArray() method, imho.

**Comment by NicoHood** [comment]
Yeah, but the header is a breaking change that should be noted in the release notes! It is no `object` anymore it is `Grav\Common\Page\Header` now. Which makes a difference as you can see!

**Comment by mahagr** [comment]
Header class has been there since 2015, but it was not used in the event before (not sure why). You should be using something like:

```php
if (!$page instanceof PageInterface) {
    return;
}

$header = $page->header();
if (!$header instanceof Header) {
    $header = new Header((array)$header);
}
```

**Comment by mahagr** [comment]
Added note to https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#pages-1

**Comment by mahagr** [comment]
Also added it to changelog.
