### ISSUE TITLE
Trying to get property 'username' of non-object

### ISSUE THREAD

**Issue by lufog** [trilbymedia/grav-plugin-flex-objects#62]
Periodically, the error ```Trying to get property 'username' of non-object``` occurs.

![image](https://user-images.githubusercontent.com/10379487/84777070-cb396b00-afe9-11ea-9d45-a23aa2fce798.png)

The error is fixed by cleaning the cookies. But after some time, the error reappears, it may become a day or a month. I am afraid that faced with such an error, the average user does not try to fix it, but simply leaves the site.

**Comment by mahagr** [comment]
This bug seems to be related to not having login plugin installed.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/60316d1b7528630a7e44754de7133c8b2b2de3f4
