### ISSUE TITLE
Can not create folder with parent other than root

### ISSUE THREAD

**Issue by MarianArlt** [trilbymedia/grav-plugin-flex-objects#66]
Grav v1.7.0-rc.13
Admin v1.10.0-rc.13
Flex Objects  v1.0.0-rc.13

I can not create new folders from the admin backend when flex-objects are enabled in paths other than root (/).
Whenever I try to create a folder as a child of another page I get a Crikey! Naming doesn't seem to matter, even the most simple string for the folder name will throw the same error:

    Error thrown with message "Call to a member function path() on null"

    Stacktrace:
    #43 Error in /srv/http/grav.cms/user/plugins/flex-objects/classes/Admin/AdminController.php:345
    #42 Grav\Plugin\FlexObjects\Admin\AdminController:taskSaveNewFolder in /srv/http/grav.cms/user/plugins/flex-objects/classes/Admin/AdminController.php:1061
    #41 Grav\Plugin\FlexObjects\Admin\AdminController:execute in /srv/http/grav.cms/user/plugins/flex-objects/flex-objects.php:247

    ../user/plugins/flex-objects/classes/Admin/AdminController.php
    344.    } else {
    345.        $path = $this->grav['page']->find($data['route'])->path();
    346.    }

**Comment by mahagr** [comment]
I marked this a bug, but I need to test it out first.
