### ISSUE TITLE
Cannot select template 'Flex-objects' on subpage

### ISSUE THREAD

**Issue by awrog** [trilbymedia/grav-plugin-flex-objects#67]
I cannot select template 'Flex-objects' on subpage.
Upon saving it is reverted to 'Default'
using plugin v1.0.0-rc.15

![flex-objects-subpage](https://user-images.githubusercontent.com/12153667/88288495-27cc2c00-ccf4-11ea-937c-5802cb78bb27.gif)

**Comment by mahagr** [comment]
This should be fixed in the upcoming version. It actually created extra file which you have to remove.
