### ISSUE TITLE
List view fields

### ISSUE THREAD

**Issue by josecarvalhoSigned** [trilbymedia/grav-plugin-flex-objects#68]
Hi, 
In the list we are receiving an integer value, but we want that when reading that integer value it makes a display of a previously defined string, almost as if it were a field of type "Select" and had to read the value in the blueprint. Does anyone know how to simulate this? Note, I don't want a select. I literally want that if the field "sw012s02" had the value "1" that appears in the text "Sold"

![image](https://user-images.githubusercontent.com/44067633/89554547-eb75f100-d806-11ea-800e-ea47cde37ec4.png)

**Comment by ricardo118** [comment]
only with a custom saving

**Comment by mahagr** [comment]
Or with a custom field type.
