### ISSUE TITLE
Flex Directory Search Breaks in Gantry5 Production Mode

### ISSUE THREAD

**Issue by thekenshow** [trilbymedia/grav-plugin-flex-objects#73]
The Flex Directory search function stops working on Grav 1.7-rc16/Gantry latest CI vdev-b3cca45fd when Gantry production mode is enabled. The Console shows the following error:

```
Uncaught ReferenceError: List is not defined
    at careers:1031
(anonymous) @ careers:1031
```

Which points to the `var flexList...` line below:

```
<script>
    var options = {
        valueNames: [ 'jobtitle', 'category', 'location', 'postdate' ]
    };
    var flexList = new List('flex-objects', options); // ERROR LINE 
</script>
``` 

Works fine when Gantry is not in production mode. For added fun, 3 days to client site launch...

**Comment by mahagr** [comment]
If you mean Flex Object page type and search in it, I just tested it and it works just fine for me (FF 81.0).

**Comment by mahagr** [comment]
Do you have JS pipeline enabled (System > Assets)? Try disabling it. If that helps, there's likely syntax error in resulting JS.

**Comment by thekenshow** [comment]
Brilliant! I disabled JS pipeline and it works fine with Gantry production mode enabled.

**Comment by thekenshow** [comment]
This is a custom particle inside a Gantry layout, not a Flex Object page type. I wonder if moving the offending JS script section out of the `templates/flex/careers/collection/accordion.html.twig` and into an atom at the bottom of the Gantry layout would help? Maybe it's being loaded before the listjs?

**Comment by mahagr** [comment]
Usually that won't help. You need to figure out why the code is broken when merged into a pipeline and fix it.

**Comment by thekenshow** [comment]
Hmmm. I have no idea how pipelining works, but the code in question was lifted straight out of this `user/plugins/flex-objects/templates/flex/contacts/collection/default.html.twig`, so I thought it would be reliable:

```
<div id="flex-objects">
  <div class="text-center">
    <input class="form-input search" type="text" placeholder="Search by name, email, etc" />
    <button class="button button-primary sort asc" data-sort="name">
      Sort by Name
    </button>
  </div>

  <ul class="list">
    {% for object in collection if object.published %}
      <li>
        {% render object layout: layout %}
      </li>
    {% endfor %}
  </ul>
</div>

<script>
    var options = {
        valueNames: [ 'name', 'email', 'website', 'entry-extra' ]
    };
    var flexList = new List('flex-objects', options);
</script>
```

Mine:

```
<div id="flex-objects" class="careers">
  <div class="text-center">
    <input class="form-input search" type="text" placeholder="Search by job title, location, etc." />
  </div>
  <ul class="list accordion" id="{{ id }}" data-accordion-id="{{ id }}">
    {% for object in collection if object.published %}
      <li id="accordion-id{{ object.key }}">
        {% render object layout: 'accordion' with { particle: particle } %}
      </li>
    {% endfor %}
  </ul>
</div>

<script>
    var options = {
        valueNames: [ 'jobtitle', 'category', 'location', 'postdate' ]
    };
    var flexList = new List('flex-objects', options);
</script>
```

**Comment by mahagr** [comment]
Not sure. Maybe run the resulting minified js files through js validator?
