### ISSUE TITLE
Sorting in the Admin Flex Users breaks on Groups

### ISSUE THREAD

**Issue by ricardo118** [trilbymedia/grav-plugin-flex-objects#76]
![2020-10-15_09-36-44](https://user-images.githubusercontent.com/7531933/96098458-09786580-0eca-11eb-8612-6db2029977e7.png)

Sorting with any other field for groups works, custom or not. Groups breaks the page with 500 request with error

 Error
`Call to protected method Grav\Common\Flex\Types\Users\UserObject::getgroups() from context 'Grav\Framework\Object\Collection\ObjectExpressionVisitor'`

**Comment by mahagr** [comment]
Groups cannot really be sorted as it's not a string but an array. Though I'm not sure why the expression visitor tries to access protected method...

**Comment by mahagr** [comment]
This is also really odd -- method_exists() should return false on protected methods...

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/d3f1f833ab7fae9bf71d03e26defc2b58fce5aeb

Looks like `method_exists()` does really not obey visibility.

**Comment by mahagr** [comment]
@ricardo118 Fixed the error, but sorting will still not work because of groups is an array.
