### ISSUE TITLE
Pages Admin: Move button opens modal which does not work

### ISSUE THREAD

**Issue by mahagr** [trilbymedia/grav-plugin-flex-objects#80]
In Pages admin, edit a page and click on [ Move ] button. Try to click on any page in there -- nothing happens (there's no AJAX call).

If you do the same from the parent form field, it works perfectly.

**Comment by w00fz** [comment]
This is fixed with https://github.com/getgrav/grav-plugin-admin/commit/d63dfc356508ad39d0c533aab6e49ebeeb483f29
