### ISSUE TITLE
Pages Admin: Copy and Move not implemented in list view

### ISSUE THREAD

**Issue by mahagr** [trilbymedia/grav-plugin-flex-objects#81]
In Pages Admin if you click on vertical `...` icon, there are options to copy and move the page. Those buttons are not implemented.

**Comment by w00fz** [comment]
Actually Move is still missing

**Comment by w00fz** [comment]
I have temporary hidden Move from the items `...` because I have a better idea for implementing both Copy and Move to allow to also pick Title / Folder and few other meaningful settings when performing the action.

This however will happen after we are live with Grav 1.7 / Admin 1.10
