### ISSUE TITLE
Pages Admin: Page Groups form field asks if you want to leave the page

### ISSUE THREAD

**Issue by mahagr** [trilbymedia/grav-plugin-flex-objects#83]
If you go to edit any page (super admin rights) and try to edit Page Groups field, FF will ask if you want to exit from the page. If you click yes, you will lose all your changes.

**Comment by w00fz** [comment]
This is fixed with https://github.com/getgrav/grav-plugin-admin/commit/01dfc8415e2d207515949a50aec7dc941ff3d02e
