### ISSUE TITLE
Function .sort() issue

### ISSUE THREAD

**Issue by ricardo118** [trilbymedia/grav-plugin-flex-objects#87]
I created a test site with 400 randomly generated flex objects, They are all labeled "testXXXX" where XXXX is a random number between 1000 and 9999

There is also a couple objects added as control, such as "ABC" "DASD" "ZYX".

When using:

```
{% set contacts = grav.get('flex').collection('contacts') %}
{% set contacts = contacts.filterBy({'published': true}).sort({nome: 'ASC'}) %}
```
As you can see, one would not expect "Laura" to be first, but rather ABC.

![image](https://user-images.githubusercontent.com/7531933/100776100-0561c200-33fc-11eb-8fb6-fbf4bc4b8512.png)

Sometimes the sorting is even weirder depending on the query result.

**Comment by mahagr** [comment]
It looks like the sorting is case sensitive, ordering looks correct though. Try out my fix in Grav core.
