### ISSUE TITLE
Flex Sorting Only works first time or only works in one direction (in Admin)

### ISSUE THREAD

**Issue by PalmTreeVI** [trilbymedia/grav-plugin-flex-objects#92]
When I click a header item for example `Name` it sorts data table in ascending order correctly

But when I click `Name` again, the ordering does not reverse table into descending order.

The direction icons to right of header item clicked does update accordingly with up or down arrows. 

Grav v1.7.0-rc.20 - Admin v1.10.0-rc.2

Here is example screen before clicking a header

![Screenshot_2020-12-20_14-08-55](https://user-images.githubusercontent.com/64500998/102777494-ab02b400-435e-11eb-873c-badf406c0b6c.png)

Here is after the first click of `Score` header

![Screenshot_2020-12-20_14-05-54](https://user-images.githubusercontent.com/64500998/102777772-409e4380-435f-11eb-89c7-64c82aec9fe3.png)

And finally, a second click of the `Score` header

![Screenshot_2020-12-20_14-06-19](https://user-images.githubusercontent.com/64500998/102777633-f7e68a80-435e-11eb-8aac-f24311a36777.png)

Notice the header direction arrows update accordingly but that the data does not change.

**Comment by w00fz** [comment]
Thanks for opening this @PalmTreeVI

**Comment by w00fz** [comment]
I can confirm the issue Matias.

To replicate, go in `/admin/accounts/users`, sort by **username** twice and you’ll notice nothing changes. However, I am sending the property `sort: username|asc` and `sort: username|desc` but it’s always returned **asc**.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/bc2435efe99b7dac9034c3f18bd33c9a119ca750
