### ISSUE TITLE
Different behavior between "old pages" and Flex Objects Admin Pages.

### ISSUE THREAD

**Issue by kiranetph** [trilbymedia/grav-plugin-flex-objects#96]
If I enable Pages (Admin) in the plugin configuration the following code does not work anymore.
```
public function onBlueprintCreated(Event $event)
    {
        $blueprint = $event['blueprint'];  
        $pages = Grav::instance()['pages'];
        $route = '/' . ltrim(Grav::instance()['admin']->route, '/');
        $page         = $pages->dispatch($route);      
    dump($page);  
```
Under Flex Objects Admin Pages the result of the dump($pages) is "null", while under the old page setting it holds the expected result.

**Comment by mahagr** [comment]
I already replied in the another issue, closing this one.
